#ifndef GL_CONST_H
#define GL_CONST_H

#define CNS_GRID "grid"
#define CNS_ROOT "root"
#define CNS_TITLE "title"
#define CNS_WIDTH "width"
#define CNS_ABSWIDTH "abs_width"
#define CNS_HEIGHT "height"
#define CNS_ABSHEIGHT "abs_height"
#define CNS_CELLSIZE "cellsize"
#define CNS_SEED "seed"
#define CNS_STARTX "startx"
#define CNS_STARTY "starty"
#define CNS_ABSSTARTX "abs_startx"
#define CNS_ABSSTARTY "abs_starty"
#define CNS_FINISHX "finishx"
#define CNS_FINISHY "finishy"
#define CNS_ABSFINISHX "abs_finishx"
#define CNS_ABSFINISHY "abs_finishy"
#define CNS_MAP "map"
#define CNS_ROW "row"
#define CNS_POINT "point"
#define CNS_X "x"
#define CNS_Y "y"
#define CNS_NUMBER "number"

#define CN_CELL_IS_BLOCKED "1"
#define CN_CELL_IS_NOT_BLOCKED "0"

#define CNS_MAPSTAT "mapstat"
#define CNS_SUMMARY "summary"
#define CNS_OBSTACLECOUNT "obstaclecount"
#define CNS_DENSITY "density"
#define CNS_TOTALAREA "totalarea"
#define CNS_TOTALPERIMETER "totalperimeter"
#define CNS_AVERAGEAREA "averagearea"
#define CNS_AVERAGEPERIMETR "averageperimeter"
#define CNS_AREADISPERSION "areadispersion"
#define CNS_PERIMETERDISPERSION "perimeterdispersion"
#define CNS_OBSTACLES "obstacles"
#define CNS_OBSTACLE "obstacle"
#define CNS_PERIMETER "perimeter"
#define CNS_AREA "area"

#endif // GL_CONST_H
